/**
 * Per-platform translation of tier manifest entries.
 *
 * Given a tier manifest (Pro / Business / future), each adapter asks this
 * module for the platform-specific block it should write. Adapters still own
 * file shape + uninstall semantics; this module only handles manifest → block.
 *
 * Keeping translation here (rather than re-implementing per adapter) means:
 *   - one place to update when manifest schema evolves
 *   - consistent behavior across adapters (no Cursor-specific drift)
 *   - Free compiler stays tier-agnostic — any tier's manifest flows through
 */

export const AUTO_SIGNATURE = '@rune-kit/rune hook-dispatch';

/**
 * Build a Claude-format block from a tier manifest.
 *
 * Returns:
 *   {
 *     hooks: { UserPromptSubmit: [...], PreToolUse: [...], ... },
 *     statusLine: { type, command, padding? } | null,
 *     notes: string[]
 *   }
 */
export function buildTierBlock(manifest, platformId) {
  if (platformId !== 'claude') {
    throw new Error(`buildTierBlock is claude-specific. For '${platformId}', use renderTierForPlatform.`);
  }

  const hooks = {};
  let statusLine = null;
  const notes = [];

  for (const entry of manifest.entries) {
    if (entry.event === 'statusLine') {
      statusLine = {
        type: 'command',
        command: entry.command,
        ...(typeof entry.padding === 'number' ? { padding: entry.padding } : {}),
      };
      continue;
    }
    // Explicit per-platform opt-out still honored even when building the Claude block
    // (keeps the check symmetric with platformEntries()).
    if (entry.platforms?.claude === 'unsupported') continue;

    const event = entry.event;
    const matcher = entry.matcher || '.*';
    if (!hooks[event]) hooks[event] = [];

    const existingGroup = hooks[event].find((g) => g.matcher === matcher);
    const hookCmd = {
      type: 'command',
      command: entry.command,
      async: entry.async === true,
    };
    if (existingGroup) {
      existingGroup.hooks.push(hookCmd);
    } else {
      hooks[event].push({ matcher, hooks: [hookCmd] });
    }
  }

  if (manifest.entries.some((e) => e.claudeOnly && e.event !== 'statusLine')) {
    notes.push(`${manifest.tier}: some entries are Claude-only and were skipped on other platforms.`);
  }

  return { hooks, statusLine, notes };
}

/**
 * Render a tier manifest entry for a rule-based platform (Cursor / Antigravity).
 * Returns null if the entry does not apply to that platform.
 */
export function renderTierRule(entry, platformId, { mode, tier }) {
  const hint = entry.platforms?.[platformId];
  if (hint === 'unsupported' || entry.claudeOnly || entry.event === 'statusLine') return null;

  const globs = entry.globs ?? defaultGlobsForEvent(entry.event);
  const alwaysApply = hint === 'rule-alwaysApply' || entry.event === 'UserPromptSubmit';

  const frontmatter = [
    '---',
    `description: Rune ${tier} ${entry.skill} — ${entry.description || 'tier hook'}`,
    `globs: ${JSON.stringify(globs)}`,
    `alwaysApply: ${alwaysApply}`,
    'rune-managed: true',
    `rune-tier: ${tier}`,
    `rune-skill: ${entry.skill}`,
    `rune-entry: ${entry.id}`,
    `mode: ${mode}`,
    '---',
  ].join('\n');

  const body = [
    `# Rune ${tier}: ${entry.skill}`,
    '',
    entry.description || `Auto-invoke ${entry.skill} when the matching edit pattern fires.`,
    '',
    `Trigger: \`${entry.event}\`${entry.matcher ? ` matcher \`${entry.matcher}\`` : ''}.`,
    `Mode: ${mode}.`,
    '',
    "On a matching operation, the agent should mentally run this skill's checklist before proceeding.",
    `See the ${tier} skill \`${entry.skill}\` for the full guidance.`,
    '',
    `_Auto-generated by \`rune hooks install --tier ${tier}\` (${AUTO_SIGNATURE})._`,
    '_Do not hand-edit — changes will be overwritten. Delete the file to opt out._',
  ].join('\n');

  return `${frontmatter}\n\n${body}\n`;
}

/**
 * Render a Windsurf workflow file for a tier entry.
 */
export function renderTierWorkflow(entry, { mode, tier }) {
  if (entry.claudeOnly || entry.event === 'statusLine' || entry.platforms?.windsurf === 'unsupported') return null;
  return [
    '---',
    `description: Rune ${tier} ${entry.skill} — ${entry.description || 'tier hook'}`,
    'rune-managed: true',
    `rune-tier: ${tier}`,
    `rune-skill: ${entry.skill}`,
    `rune-entry: ${entry.id}`,
    `mode: ${mode}`,
    '---',
    '',
    `# /rune-${tier}-${entry.skill}`,
    '',
    entry.description || `Run before ${entry.event} operations.`,
    '',
    '## Steps',
    '',
    `1. Review target context for ${entry.skill} concerns.`,
    `2. Apply Rune ${tier} skill guidance (see \`${tier}/skills/${entry.skill}/SKILL.md\`).`,
    `3. Surface any finding — mode ${mode}.`,
    '',
    `_Auto-generated by \`rune hooks install --tier ${tier}\` (${AUTO_SIGNATURE})._`,
    '',
  ].join('\n');
}

/**
 * Filter which entries a platform should emit rules/workflows for.
 * Statusline + claudeOnly entries are filtered out centrally.
 */
export function platformEntries(manifest, platformId) {
  return manifest.entries.filter((entry) => {
    if (entry.event === 'statusLine') return false;
    if (entry.claudeOnly) return false;
    const hint = entry.platforms?.[platformId];
    if (hint === 'unsupported') return false;
    return true;
  });
}

/**
 * Unsupported / skipped entries — exposed so adapters can report them via notes.
 */
export function unsupportedEntries(manifest, platformId) {
  return manifest.entries.filter((entry) => {
    if (entry.claudeOnly && platformId !== 'claude') return true;
    if (entry.event === 'statusLine' && platformId !== 'claude') return true;
    const hint = entry.platforms?.[platformId];
    return hint === 'unsupported';
  });
}

function defaultGlobsForEvent(event) {
  switch (event) {
    case 'UserPromptSubmit':
      return ['**/*'];
    case 'PreToolUse':
    case 'PostToolUse':
      return ['**/*.ts', '**/*.tsx', '**/*.js', '**/*.jsx', '**/*.py', '**/*.go', '**/*.rs', '**/*.md'];
    case 'Stop':
      return ['**/*'];
    default:
      return ['**/*'];
  }
}
