/**
 * Aider Adapter
 *
 * Emits per-skill convention files into aider/rules/ and a `.aider.conf.yml`
 * at the project root with a `read:` array pointing to every rule file. Aider
 * loads everything in `read:` automatically on each session.
 *
 * Aider rules dir: aider/rules/
 * Aider rule file: aider/rules/rune-{name}.md
 * Aider config: .aider.conf.yml (auto-discovered: home dir → repo root → cwd)
 *
 * @see https://aider.chat/docs/usage/conventions.html
 * @see https://aider.chat/docs/config/aider_conf.html
 *
 * MODEL TIER MAPPING (v2.18+):
 * Aider supports any provider via env vars / CLI flags. Tier hint is emitted
 * as a comment — aider does not parse model directives from rule files.
 */

import { BRANDING_FOOTER } from '../transforms/branding.js';

const MODEL_MAP = {
  opus: 'tier:heavy',
  sonnet: 'tier:mid',
  haiku: 'tier:light',
};

const TOOL_MAP = {
  Read: 'read the file',
  Write: 'write/create the file',
  Edit: 'edit the file',
  Glob: 'find files by pattern',
  Grep: 'search file contents',
  Bash: 'run a shell command',
  TodoWrite: 'track task progress',
  Skill: 'follow the referenced rune-{name} convention',
  Agent: 'execute the workflow',
};

export default {
  name: 'aider',
  outputDir: 'aider/rules',
  fileExtension: '.md',
  skillPrefix: 'rune-',
  skillSuffix: '',

  // Aider conventions are flat per-skill markdown files.
  useSkillDirectories: false,

  transformReference(skillName, raw) {
    const isBackticked = raw.startsWith('`') && raw.endsWith('`');
    const ref = `the rune-${skillName} convention`;
    return isBackticked ? `\`${ref}\`` : ref;
  },

  transformToolName(toolName) {
    return TOOL_MAP[toolName] || toolName;
  },

  generateHeader(skill) {
    const tierHint = skill.model ? MODEL_MAP[skill.model] || skill.model : null;
    const tierLine = tierHint ? ` | ${tierHint}` : '';
    return `# rune-${skill.name}\n\n> Rune ${skill.layer} ${skill.group}${tierLine}\n> ${(skill.description || '').replace(/\n/g, ' ')}\n\n`;
  },

  generateFooter() {
    return BRANDING_FOOTER;
  },

  transformSubagentInstruction(text) {
    return text;
  },

  scriptsDir(skillName) {
    return `rune-${skillName}-scripts`;
  },

  postProcess(content) {
    return content.replace(/^context: fork\n/gm, '').replace(/^agent: general-purpose\n/gm, '');
  },

  // Emit `.aider.conf.yml` with `read:` array referencing every rule file +
  // a CONVENTIONS.md as the high-level entry point.
  generateExtraFiles({ stats }) {
    // stats.files holds entries like 'rune-cook.md' (per-skill) and 'index.md' (autogen).
    // Filter to per-skill rule files; aider loads everything in read[] on every session.
    const ruleFiles = stats.files
      .filter((f) => f.startsWith('rune-') && f.endsWith('.md') && !f.includes('/') && !f.includes('\\'))
      .sort();

    const conf = [
      '# Auto-generated by Rune — do not edit manually.',
      '# Aider auto-loads every file listed under `read:` on each session.',
      'read:',
      ...ruleFiles.map((f) => `  - aider/rules/${f}`),
      '',
    ].join('\n');

    const conventions = [
      '# Rune Conventions for Aider',
      '',
      `Rune compiles ${stats.skillCount} skills + ${stats.packCount} packs into per-skill convention files under \`aider/rules/\`. Aider auto-loads them via \`.aider.conf.yml\`.`,
      '',
      'When a request matches a skill (e.g. "implement", "refactor", "review"), follow the matching rune-<name> convention.',
      '',
      '## Loaded Conventions',
      '',
      ...ruleFiles.map((f) => `- \`aider/rules/${f}\``),
      '',
      '---',
      '> Rune Skill Mesh — https://github.com/rune-kit/rune',
      '',
    ].join('\n');

    return [
      { path: '.aider.conf.yml', content: conf },
      { path: 'CONVENTIONS.md', content: conventions },
    ];
  },
};
